# Generated by Django 5.0.6 on 2024-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user_table',
            name='firstname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user_table',
            name='lastname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
