# Generated by Django 5.0.6 on 2024-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_user_table_mobile_user_table_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='Address',
            field=models.TextField(default=None),
        ),
    ]
