# Generated by Django 5.0.6 on 2024-06-29 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_table_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Total_price', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.user_table')),
            ],
        ),
    ]
