# Generated by Django 5.0.6 on 2024-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
